@startuml
skinparam monochrome true

title NORMALINTRSIGENA Register (Offset: 0x0038) - Access: Read/Write

map "NORMALINTRSIGENA" as reg {
  15 => NORMALINTRSTS_ENABLEREGBIT0
  14 => NORMALINTRSTS_ENABLEREGBIT1
  13 => NORMALINTRSTS_ENABLEREGBIT2
  12 => NORMALINTRSTS_ENABLEREGBIT3
  11 => NORMALINTRSTS_ENABLEREGBIT4
  10 => NORMALINTRSTS_ENABLEREGBIT5
  9 => SDHCREGSET_CARDINSTSENA
  8 => SDHCREGSET_CARDREMSTSENA
  7 => SDHCREGSET_CARDINTSTSENA
  6 => NORMALINTRSTS_ENABLEREGBIT9
  5 => NORMALINTRSTS_ENABLEREGBIT10
  4 => NORMALINTRSTS_ENABLEREGBIT11
  3 => NORMALINTRSTS_ENABLEREGBIT12
  2 => NORMALINTRSTS_ENABLEREGBIT13
  1 => NORMALINTRSTS_ENABLEREGBIT14
  0 => NORMALINTRSTS_ENABLEREGBIT15
}

note bottom of reg
  Reset Value: All bits = 0
  
  R = Read
  W = Write
end note
@enduml