@startuml
skinparam monochrome true
skinparam defaultFontName Arial

title Figure 1866. ADMA System address n register (ADMASYSADDRn)

note top of map
Offset: 0x0058 + n*0x2 (n=0 to 3)
Access: Read/Write
end note

map "ADMASYSADDRn" as reg {
}

rectangle "16-bit Register" {
    rectangle "R\nW" as RW #white
    
    collections "Bit 15-0" as bits
    
    note bottom of bits
    |= Bit |= 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1 | 0 |
    |= R/W | ADMA_SYSADDRESS |||||||||||||||| 
    |= Reset | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
    end note
}

@enduml