@startuml
skinparam monochrome true
skinparam defaultFontName Courier

title Figure 1850. Normal interrupt status enable register (NORMALINTRSTSENA)

note as header
Offset: 0x0034
Access: Read/Write
end note

map "NORMALINTRSTSENA" as reg {
  15 => NORMALINTRSTS_ENABLEREGBIT15
  14 => NORMALINTRSTS_ENABLEREGBIT14
  13 => NORMALINTRSTS_ENABLEREGBIT13
  12 => NORMALINTRSTS_ENABLEREGBIT12
  11 => NORMALINTRSTS_ENABLEREGBIT11
  10 => NORMALINTRSTS_ENABLEREGBIT10
  9 => NORMALINTRSTS_ENABLEREGBIT9
  8 => SDHCREGSET_CARDINTSTSENA
  7 => SDHCREGSET_CARDREMSTSENA
  6 => SDHCREGSET_CARDINSTSENA
  5 => NORMALINTRSTS_ENABLEREGBIT5
  4 => NORMALINTRSTS_ENABLEREGBIT4
  3 => NORMALINTRSTS_ENABLEREGBIT3
  2 => NORMALINTRSTS_ENABLEREGBIT2
  1 => NORMALINTRSTS_ENABLEREGBIT1
  0 => NORMALINTRSTS_ENABLEREGBIT0
}

note bottom of reg
Reset values: All bits = 0
R = Read, W = Write
end note

@enduml