@startuml
concise "DAT line" as DAT
concise "Read Wait" as RW
concise "Stop At Block Gap Request (Control)" as SABGR
concise "Continue Request (Control)" as CR
concise "DAT Line Active (Status)" as DLA
concise "Read Transfer Active (Status)" as RTA
concise "Block Gap Event (Interrupt)" as BGE
concise "Transfer Complete (Interrupt)" as TC

@0
DAT is idle
RW is low
SABGR is low
CR is low
DLA is low
RTA is low
BGE is low
TC is low

@10
DAT is active
RW is high

@30
DAT is "Last block"

@40
RW is low

@50
SABGR is high

@55
DLA is high

@60
RTA is high

@70
DLA is low
RTA is low

@75
TC is high

@80
TC is low

@enduml