@startuml
!define RECTANGLE rectangle

start

:Enable Int or Card Detect;

note right
  (1)
end note

:Wait for Card Detect Int occur;

note right
  (2)
end note

:Clr Card Detect Int Status;

note left
  (3)
end note

if (Check\nCard Inserted) then (Card Inserted is 1b,\nthen recognize as insertion)
  
else (Card Inserted is 0b,\nthen recognize as removal)
  
endif

stop

@enduml