@startuml
skinparam backgroundColor white
skinparam rectangleBorderColor black
skinparam rectangleFontSize 10
skinparam defaultTextAlignment center

rectangle "Block Gap Control Register (Offset 02Ah)" {
  
  map RegisterLayout {
    D07-D04 => Rsvd
    D03 => Interrupt At Block\nGap
    D02 => Read Wait Control
    D01 => Continue Request
    D00 => Stop At Block Gap\nRequest
  }
  
}

package "Register Field Details" {
  
  card "D07-D04: Reserved (Rsvd)" as field_rsvd
  
  card "D03: Interrupt At Block Gap (RW)" as field_d03 {
    **Interrupt At Block Gap**
    This bit is valid only in 4-bit mode of the SDIO card and selects a sample point in
    the interrupt cycle. Setting to 1 enables interrupt detection at the block gap for a
    multiple block transfer. Setting to 0 disables interrupt detection during a multiple
    block transfer. If the SD card cannot signal an interrupt during a multiple block
    transfer, this bit should be set to 0. When the Host Driver detects an SD card
    insertion, it shall set this bit according to the CCCR of the SDIO card.
    ---
    1 = Enabled
    0 = Disabled
  }
  
  card "D02: Read Wait Control (RW)" as field_d02 {
    **Read Wait Control**
    The read wait function is optional for SDIO cards. If the card supports read wait,
    set this bit to enable use of the read wait protocol to stop read data using the
    **DAT[2]** line. Otherwise, the Host Controller has to stop the SD Clock to hold read
    data, which restricts commands generation. When the Host Driver detects an SD
    card insertion, it shall set this bit according to the CCCR of the SDIO card. If the
    card does not support read wait, this bit shall never be set to 1 otherwise **DAT** line
    conflict may occur. If this bit is set to 0, Suspend/Resume cannot be supported.
    ---
    1 = Enable Read Wait Control
    0 = Disable Read Wait Control
  }
  
  card "D01: Continue Request (RWAC)" as field_d01 {
    **Continue Request**
    This bit is used to restart a transaction, which was stopped using the **Stop At**
    **Block Gap Request**. To cancel stop at the block gap, set **Stop At Block Gap**
    **Request** to 0 and set this bit 1 to restart the transfer.
    The Host Controller automatically clears this bit in either of the following cases:
    (1) In the case of a read transaction, the **DAT Line Active** changes from 0 to 1
        as a read transaction restarts.
    (2) In the case of a write transaction, the **Write Transfer Active** changes from 0
        to 1 as the write transaction restarts.
    Therefore, it is not necessary for Host Driver to set this bit to 0. If **Stop At Block**
    **Gap Request** is set to 1, any write to this bit is ignored.
    ---
    1 = Restart
    0 = Not affect
  }
  
  card "D00: Stop At Block Gap Request (RW)" as field_d00 {
    **Stop At Block Gap Request**
    This bit is used to stop executing read and write transaction at the next block gap
    for non-DMA, SDMA and ADMA transfers. The Host Driver shall leave this bit set
  }
  
}

RegisterLayout -[hidden]down- field_rsvd
field_rsvd -[hidden]down- field_d03
field_d03 -[hidden]down- field_d02
field_d02 -[hidden]down- field_d01
field_d01 -[hidden]down- field_d00

@enduml