@startuml
skinparam ActivityBackgroundColor Yellow
skinparam ActivityBorderColor Black

start
:CMD0;
:CMD8;
:ACMD41 HCS=1, S18R=1;

if (Check busy) then (No Response)
  stop
elseif (D31=0 (busy)) then
  :ACMD41 HCS=1, S18R=1;
  note right: Repeat
else (D31=1 (Completed))
  :Check CCS;
  if () then (CCS=0 (SDSC))
    :CMD2;
    :CMD3;
    :CMD7;
    :CMD42;
    :ACMD6;
    note right: 4-bit mode
    if (UHS-I Card?) then (No)
    else (Yes)
      :CMD6\nFunction Group 3;
      note right: Driver Strength
      :CMD6\nFunction Group 1, 4;
      note right: UHS-I Mode | Current Limit
      :CMD19;
      while (Complete?) is (No)
        :Tuning;
      endwhile (Yes)
    endif
    stop
  else (CCS=1 (SDHC/SDXC))
    :Check S18A;
    if () then (S18A=0 (No Switch))
      :CMD2;
      :CMD3;
      :CMD7;
      :CMD42;
      :ACMD6;
      note right: 4-bit mode
      if (UHS-I Card?) then (No)
      else (Yes)
        :CMD6\nFunction Group 3;
        note right: Driver Strength
        :CMD6\nFunction Group 1, 4;
        note right: UHS-I Mode | Current Limit
        :CMD19;
        while (Complete?) is (No)
          :Tuning;
        endwhile (Yes)
      endif
      stop
    else (S18A=1 (Switch))
      :CMD11;
      if (Check Resp.) then (No Response)
        stop
      else (Get Response)
        :Voltage Switch Sequence\nSwitch to SDR12 timing;
        if (Error?) then (Yes)
          #Pink:Power Cycle;
          note left: Switch Error
          stop
        else (No)
          note right: 1.8V Signal    UHS-I Mode
          :CMD2;
          :CMD3;
          :CMD7;
          :CMD42;
          :ACMD6;
          note right: 4-bit mode
          if (UHS-I Card?) then (No)
          else (Yes)
            :CMD6\nFunction Group 3;
            note right: Driver Strength
            :CMD6\nFunction Group 1, 4;
            note right: UHS-I Mode | Current Limit
            :CMD19;
            while (Complete?) is (No)
              :Tuning;
            endwhile (Yes)
          endif
          stop
        endif
      endif
    endif
  endif
endif

@enduml