@startuml
robust "CLK" as CLK
robust "Input" as Input
robust "Output" as Output

scale 1 as 150 pixels

@0
CLK is low
Input is Data
Output is Data

@100
CLK is high
Input is Data

@200
CLK is high
Input is Invalid
Output is Invalid

@300
CLK is low
Input is Invalid
Output is Invalid

@400
CLK is low
Input is Data
Output is Data

@500
CLK is high
Input is Data
Output is Data

@enduml