@startuml
robust "CMD" as CMD

@0
CMD is {S}

@1
CMD is {T}

@2
CMD is {Content}

@6
CMD is {CRC}

@9
CMD is {E}

@10
CMD is {Z}

@11
CMD is {*,*,*}

@14
CMD is {Z}

@15
CMD is {S}

@16
CMD is {T}

@17
CMD is {Content}

@21
CMD is {CRC}

@24
CMD is {E}

@25
CMD is {Z}

@26
CMD is {Z}

@27
CMD is {Z}

note top of CMD
  |<- Host Command ->|<- N_CR cycles ->|<- Response ->|
end note

@enduml